import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import classNames from 'classnames';
import type { Metadata } from 'next';
import type { FC, PropsWithChildren } from 'react';

import { VERCEL_ENV } from '@/lib/constants.mjs';
import { GEIST_MONO, GEIST_SANS, SPACE_GROTESK } from '@/lib/fonts.mjs';

import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const FONTS = classNames(GEIST_SANS.variable, GEIST_MONO.variable, SPACE_GROTESK.variable);

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html className={FONTS} lang="en">
			<body>
				{children}

				{/* Only load Analytics on production */}
				{VERCEL_ENV === 'production' && <Analytics />}

				{/* Get Speed Insights on every Vercel environment */}
				{VERCEL_ENV && <SpeedInsights />}
			</body>
		</html>
	);
};

export default RootLayout;
