import './globals.css';
import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google';
import Axe from './Axe';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: {
		template: '%s | LabelNoir'
	},
	description: 'Generated by create next app',
	metadataBase: new URL(`https://${process.env.VERCEL_URL}`),
	themeColor: '#0A0A0A',
	robots: {
		index: false,
		follow: false,
		nocache: true
	}
};

export default async function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main>
					{children}
				</main>

				{/* Scripts */}
				<Axe />
				<Analytics />
			</body>
		</html>
	);
}
