// Imports
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import classNames from 'classnames';
import type { Metadata, Viewport } from 'next';
import '@/styles/global.css';
import type { FC, PropsWithChildren } from 'react';

import AxeCore from '@/components/Abstracts/a11y';
import AnimateOnScroll from '@/components/Abstracts/aos';
import { IS_DEVELOPMENT, VERCEL_ENV } from '@/lib/constants';
import { GEIST_MONO, GEIST_SANS, SPACE_GROTESK, SPACE_MONO } from '@/lib/fonts';
import Footer from 'UI/Footer';
import Navigation from 'UI/Navigation';

// Meta Data
export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	viewportFit: 'cover',
	themeColor: '#060606',
};

export const metadata: Metadata = {
	title: 'LabelNoir.me',
	description: 'Generated by create next app',
};

// Helpers
const FONTS = classNames(
	GEIST_MONO.variable,
	GEIST_SANS.variable,
	SPACE_GROTESK.variable,
	SPACE_MONO.variable
);

// Layout component
const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html className={classNames('scroll-pt-48 scroll-smooth', FONTS)} lang="en">
			<body className="flex min-h-svh flex-col items-center bg-noir-900 text-noir-300 selection:bg-noir-50 selection:text-noir-900">
				<AnimateOnScroll />

				<Navigation />

				{children}

				<Footer />

				{/* Only load Axe Core on development */}
				{IS_DEVELOPMENT && <AxeCore />}

				{/* Only load Analytics on production */}
				{VERCEL_ENV === 'production' && <Analytics />}

				{/* Get Speed Insights on every Vercel environment */}
				{VERCEL_ENV && <SpeedInsights />}
			</body>
		</html>
	);
};

// Exports
export default RootLayout;
