import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import classNames from 'classnames';
import type { Metadata, Viewport } from 'next';
import '@/styles/global.css';
import type { FC, PropsWithChildren } from 'react';

import AxeCore from '@/components/Abstracts/a11y';
import AnimateOnScroll from '@/components/Abstracts/aos';
import Footer from '@/components/UI/Footer';
import Navigation from '@/components/UI/Navigation';
import { IS_DEVELOPMENT, VERCEL_ENV } from '@/lib/constants.mjs';
import { GEIST_MONO, GEIST_SANS, SPACE_GROTESK } from '@/lib/fonts.mjs';

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	viewportFit: 'cover',
	themeColor: '#060606',
};

export const metadata: Metadata = {
	title: 'LabelNoir.me',
	description: 'Generated by create next app',
};

const FONTS = classNames(GEIST_MONO.variable, GEIST_SANS.variable, SPACE_GROTESK.variable);

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html className={FONTS} lang="en">
			<body className="bg-noir-900 text-noir-300">
				<AnimateOnScroll />

				<Navigation />

				{children}

				<Footer />

				{/* Only load Axe Core on development */}
				{IS_DEVELOPMENT && <AxeCore />}

				{/* Only load Analytics on production */}
				{VERCEL_ENV === 'production' && <Analytics />}

				{/* Get Speed Insights on every Vercel environment */}
				{VERCEL_ENV && <SpeedInsights />}
			</body>
		</html>
	);
};

export default RootLayout;
