import './globals.css';
import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google';
import Axe from './Axe';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
	return [{ locale: 'en' }, { locale: 'nl' }];
}

export const metadata = {
	title: {
		template: '%s | LabelNoir',
	},
	description: 'Generated by create next app',
	metadataBase: new URL(`https://${process.env.VERCEL_URL}`),
	themeColor: '#0A0A0A',
	robots: {
		index: false,
		follow: false,
		nocache: true,
	},
};

export default async function RootLayout({ children, params: { locale } }) {
	// Fetch active translation for client side components
	let messages;
	try {
		messages = (await import(`./dictionaries/${locale}.json`)).default;
	} catch (error) {
		notFound();
	}

	return (
		<html lang="en">
			<body className={inter.className}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					<main>{children}</main>
				</NextIntlClientProvider>

				{/* Scripts */}
				<Axe />
				<Analytics />
			</body>
		</html>
	);
}
